[theme]
primaryColor="#0366d6"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f7f7f7"
textColor="#333333"
font="sans serif"

[server]
enableStaticServing = true
runOnSave = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[global]
developmentMode = false
logLevel = "info" 